[project]
name = "proj-herritage-tree"
version = "0.1.0"
description = ""
authors = [
    {name = "Experiences",email = "113293259+ExperiencesXP@users.noreply.github.com"},
    {name = "Blockgameentity",email = "git@desu.re"},
    {name = "Lufnin",email="idk@example.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
pytest = "^8.3"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["src/tests"]
